INSERT INTO books(title, author, publication, link) VALUES('El Quijote', 'Miguel de Cervantes', '2020-11-01','https://www.cervantesvirtual.com/obra/el-ingenioso-hidalgo-don-quijote-de-la-mancha-2012/');
INSERT INTO books(title, author, publication, link) VALUES('El perro del hortelano', 'Lope de Vega', '2019-11-01','https://www.cervantesvirtual.com/obra/el-perro-del-hortelano--0/');
INSERT INTO books(title, author, publication, link) VALUES('Fuenteovejuna', 'Lope de Vega', '2018-11-01,'https://www.cervantesvirtual.com/obra/fuente-ovejuna--1/');
INSERT INTO books(title, author, publication, link) VALUES('La dama boba', 'Lope de Vega', '2017-11-01','https://www.cervantesvirtual.com/obra/la-dama-boba--0/');
INSERT INTO books(title, author, publication, link) VALUES('El caballero de Olmedo', 'Lope de Vega', '2016-11-01','https://www.cervantesvirtual.com/obra/el-caballero-de-olmedo--0/');
INSERT INTO books(title, author, publication) VALUES('Antología Poética', 'Gertrudis Gómez de Avellaneda', '1869-11-01');
INSERT INTO books(title, author, publication, link) VALUES('Cuentos de la patria', 'Emilia Pardo Bazán', '1963-11-01','https://www.cervantesvirtual.com/obra/cuentos-de-la-patria--0/');
INSERT INTO books(title, author, publication) VALUES('Mujeres: Vidas paralelas', 'Concepción Gimeno de Flaquer', '1893-11-01');
INSERT INTO books(title, author, publication) VALUES('Conto gallego', 'Rosalía de Castro', '1903-11-01');
INSERT INTO books(title, author, publication, link) VALUES('La casa de muñecas', 'Rosario de Acuña', '1988-11-01','https://www.cervantesvirtual.com/obra/la-casa-de-munecas/');
INSERT INTO books(title, author, publication, link) VALUES('Rienzi el Tribuno', 'Rosario de Acuña', '1999-11-01','https://www.cervantesvirtual.com/obra/rienzi-el-tribuno--1/');
INSERT INTO books(title, author, publication) VALUES('El paranocaidas', 'Gloria Fuertes', '2003-11-01');
INSERT INTO books(title, author, publication, link) VALUES('Munio Alfonso : drama trágico original en cuatro actos y en verso', 'Gertrudis Gómez de Avellaneda', '1869-11-01','https://www.cervantesvirtual.com/obra/munio-alonso-drama-tragico-original-en-cuatro-actos-y-en-verso--0/');
INSERT INTO books(title, author, publication, link) VALUES('Saúl : drama bíblico en cuatro actos y en verso', 'Gertrudis Gómez de Avellaneda', '1869-11-01','https://www.cervantesvirtual.com/obra/saul-drama-biblico-en-cuatro-actos-y-en-verso--0/');
INSERT INTO books(title, author, publication) VALUES('La ondina del lago azul : recuerdo de mi última excursión por los Pirineos', 'Gertrudis Gómez de Avellaneda', '1871-11-01');